version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    volumes:
      - .:/usr/src/app
    container_name: node-dev
    command: node server.js
